<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    {{-- Fonts --}}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    {{-- Hanken Grotesk --}}
    <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet">
    <title>Attendance Report - {{ $selectedSchoolYear }}</title>
    <style>
        body {
            font-family: Hanken Grotesk, sans-serif;
            font-size: 12px;
            margin: 40px;
            color: #000;
        }
        header {
            display: flex;
            align-items: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        header img {
            height: 70px;
        }
        header .header-text {
            flex: 1;
            text-align: center;
        }
        h1 {
            font-size: 18px;
            margin: 0;
        }
        h2 {
            font-size: 16px;
            margin: 5px 0 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .footer {
            margin-top: 40px;
            font-size: 12px;
            text-align: center;
            border-top: 1px solid #000;
            padding-top: 10px;
        }
    </style>
</head>
<body>

    <header>
        <div style="text-align: center; margin-bottom: 10px;">
            <img src="{{ public_path('images/MKDGJ.png') }}" alt="Logo">
        </div>
        <div class="header-text">
            <h1>MINDANAO KOKUSAI DAIGAKU</h1>
            {{-- <h1 style="font-size: 14px;">(Mindanao International College)</h1> --}}
            <h1 style="margin-top:5px;">STUDENT AFFAIRS AND SERVICES OFFICE (SASO)</h1>
            <h2 style="margin-top:20px;">ATTENDANCE REPORT - SCHOOL YEAR {{ $selectedSchoolYear }}</h2>
        </div>
    </header>

    <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F d, Y') }}</p>

    {{-- Yearly Rates Summary --}}
    <h3 style="margin-top: 30px;">Overall Attendance Rates (A.Y. {{ $selectedSchoolYear }})</h3>
    <table>
        <thead>
            <tr>
                <th>Present Rate</th>
                <th>Late Rate</th>
                <th>Absent Rate</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $presentPercent }}%</td>
                <td>{{ $latePercent }}%</td>
                <td>{{ $absentPercent }}%</td>
            </tr>
        </tbody>
    </table>

    @if($hasEvents)
        <table>
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Total Events</th>
                    <th>Total Attendees</th>
                    <th>Present</th>
                    <th>Late</th>
                    <th>Absent</th>
                </tr>
            </thead>
            <tbody>
                @foreach($eventSummary as $row)
                    <tr>
                        <td>{{ $row['event_title'] }}</td>
                        <td>{{ \Carbon\Carbon::parse($row['date'])->format('F d, Y') }}</td>
                        <td>{{ $row['total_attendees'] }}</td>
                        <td>{{ $row['present'] }}</td>
                        <td>{{ $row['late'] }}</td>
                        <td>{{ $row['absent'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    @else
        <p style="text-align: center; margin-top: 50px; font-weight: bold;">
            No events recorded for the selected school year.
        </p>
    @endif

    <div class="footer">
        <p>Generated by SHUSSEKI Events Management System</p>
    </div>

</body>
</html>
