<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance Report - {{ $event->title }}</title>
    <style>
        body { font-family: Hanken Grotesk, sans-serif; font-size: 12px; margin: 40px; color: #000; }
        header { display: flex; align-items: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
        header img { height: 70px; }
        header .header-text { flex: 1; text-align: center; }
        h1 { font-size: 18px; margin: 0; }
        h2 { font-size: 16px; margin: 5px 0 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #000; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .footer { margin-top: 40px; font-size: 12px; text-align: center; border-top: 1px solid #000; padding-top: 10px; }
    </style>
</head>
<body>

<header>
    <div style="text-align: center; margin-bottom: 10px;">
        <img src="{{ public_path('images/MKDGJ.png') }}" alt="Logo">
    </div>
    <div class="header-text">
        <h1>MINDANAO KOKUSAI DAIGAKU</h1>
        {{-- <h1 style="font-size: 14px;">(Mindanao International College)</h1> --}}
        <h1 style="margin-top:5px;">STUDENT AFFAIRS AND SERVICES OFFICE (SASO)</h1>
        <h2 style="margin-top:20px;">ATTENDANCE REPORT</h2>
    </div>
</header>

<p><strong>Generated on:</strong> {{ \Carbon\Carbon::now()->format('F d, Y') }}</p>

<h3 style="margin-top:30px; font-size: 18px;">{{ $event->title }}</h3>
<h3 style="font-size: 18px;">({{ \Carbon\Carbon::parse($event->date)->format('F d, Y') }})</h3>

{{-- Summary --}}
<h3 style="margin-top:30px;">Event Attendance Summary</h3>
<table>
    <thead>
        <tr>
            <th>Total Attendees</th>
            <th>Present</th>
            <th>Late</th>
            <th>Absent</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ $totalAttendees }}</td>
            <td>{{ $presentCount }}</td>
            <td>{{ $lateCount }}</td>
            <td>{{ $absentCount }}</td>
        </tr>
    </tbody>
</table>

{{-- Detailed List --}}
<h3 style="margin-top:20px;">Attendee List</h3>
<table>
    <thead>
        <tr>
            <th>Student Name</th>
            <th>Year Level</th>
            <th>Course</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($logs as $log)
            <tr>
                <td>{{ $log->user->name }}</td>
                <td>{{ $log->user->year_level ?? 'N/A' }}</td>
                <td>{{ $log->user->course ?? 'N/A' }}</td>
                <td>{{ ucfirst($log->attendance_status->value) }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    <p>Generated by SHUSSEKI Events Management System</p>
</div>

</body>
</html>
